POST http://localhost:5000/api/authen/signin
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "12345"
}

###

POST http://localhost:5000/api/authen/signup
Content-Type: application/json

{
    "email": "abcdefg@gmail.com",
    "password": "12345"
}